from setuptools import setup, find_packages

setup(
    name="yap-sdk",
    version="1.0.0",
    description="Python bindings for the YAP API",
    long_description="The YAP Python library provides convenient access to the YAP API from applications written in the Python language.",
    long_description_content_type="text/x-rst",
    author="youngapp",
    author_email="support@youngapp.co",
    url="https://github.com/youngapp/yap-python",
    license="MIT",
    keywords="youngapp api machine learning ocr",
    packages=find_packages(exclude=["tests", "tests.*"]),
    zip_safe=False,
    install_requires=[
        'requests >= 2.20; python_version >= "3.0"',
        'requests[security] >= 2.20; python_version < "3.0"',
    ],
    python_requires=">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*",
    project_urls={
        "Bug Tracker": "https://github.com/youngapp/yap-python/issues",
        "Documentation": "https://developer.youngapp.co",
        "Source Code": "https://github.com/youngapp/yap-python",
    },
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.4",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: Implementation :: PyPy",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
)
